// Package store walks the runtime directory (typically ~/.sunny) and
// builds an in-memory index of agents, their knowledge files, and their skills.
//
// CRUD: Create, Update, Delete mutate both the in-memory map and the
// filesystem so callers (HTTP handlers) only need to call one method.
// Operations are serialized through an RWMutex.
//
// Identity model (v0.19+): every agent has an opaque immutable ID
// (agent.NewID — shape agt_<ts>_<hex>). The ID doubles as the
// directory name on disk. The display name lives in agent.yaml and
// can be edited freely without moving any files.
package store

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/noesrafa/sunny/internal/agent"
	"github.com/noesrafa/sunny/internal/avatar"
	"github.com/noesrafa/sunny/internal/skill"
)

// ErrNotFound is returned by mutators when no agent matches the given id.
var ErrNotFound = errors.New("agent not found")

// ErrConflict is returned by Create when the id is already taken.
var ErrConflict = errors.New("agent already exists")

type Agent struct {
	ID                  string
	Dir                 string
	Config              *agent.Config
	Knowledge           []KnowledgeFile
	KnowledgeCategories []Category
	Skills              []*skill.Skill
	SkillCategories     []Category
	// Prompt is the contents of prompt.md (the agent's persona). Loaded
	// once at boot; CRUD keeps it in sync.
	Prompt string
	// HasAvatar reflects whether avatar.webp exists in Dir at load
	// time. Mutating endpoints (PUT/DELETE /avatar) keep this in sync
	// without a full reload.
	HasAvatar bool
}

// Category is a top-level subdirectory of skills/ or knowledge/.
// Description is the first non-empty, non-heading line of an
// optional INDEX.md inside the directory.
type Category struct {
	Name        string
	Description string
}

type KnowledgeFile struct {
	Name     string // relative path under knowledge/, e.g. "general/about.md"
	Category string // top-level subdir name under knowledge/
	Path     string // absolute path on disk
}

type Store struct {
	Root   string
	mu     sync.RWMutex
	agents map[string]*Agent
}

func (s *Store) Agents() []*Agent {
	s.mu.RLock()
	defer s.mu.RUnlock()
	out := make([]*Agent, 0, len(s.agents))
	for _, a := range s.agents {
		out = append(out, a)
	}
	// Sort by display name (case-insensitive) — that's what the user
	// sees in the picker. ID order is meaningless to humans now that
	// IDs are opaque.
	sort.Slice(out, func(i, j int) bool {
		return strings.ToLower(out[i].Config.Name) < strings.ToLower(out[j].Config.Name)
	})
	return out
}

func (s *Store) Agent(id string) (*Agent, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	a, ok := s.agents[id]
	return a, ok
}

// Create scaffolds a new agent on disk and registers it in the index.
// The id is generated by the store (callers don't supply one) so
// creation can never collide with an existing dir. Returns the
// freshly-loaded *Agent.
func (s *Store) Create(cfg agent.Config, prompt string) (*Agent, error) {
	if cfg.Name == "" {
		return nil, fmt.Errorf("agent: name is required")
	}
	if cfg.Model == "" {
		return nil, fmt.Errorf("agent: model is required")
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	// Generate a fresh id; in the (vanishingly unlikely) event of a
	// collision, retry once. After two collisions something is wrong
	// and we'd rather fail loud.
	var id string
	for attempt := 0; attempt < 2; attempt++ {
		generated, err := agent.NewID()
		if err != nil {
			return nil, fmt.Errorf("generate id: %w", err)
		}
		if _, exists := s.agents[generated]; !exists {
			id = generated
			break
		}
	}
	if id == "" {
		return nil, fmt.Errorf("%w: id collision", ErrConflict)
	}
	cfg.ID = id

	if err := cfg.Validate(); err != nil {
		return nil, err
	}

	dir := filepath.Join(s.Root, "agents", id)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, fmt.Errorf("mkdir agent dir: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(dir, "knowledge"), 0o755); err != nil {
		return nil, fmt.Errorf("mkdir knowledge: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(dir, "skills"), 0o755); err != nil {
		return nil, fmt.Errorf("mkdir skills: %w", err)
	}
	if err := agent.SaveConfig(dir, &cfg); err != nil {
		return nil, err
	}
	if err := os.WriteFile(filepath.Join(dir, "prompt.md"), []byte(prompt), 0o644); err != nil {
		return nil, fmt.Errorf("write prompt.md: %w", err)
	}

	a, err := loadAgent(dir)
	if err != nil {
		return nil, fmt.Errorf("reload after create: %w", err)
	}
	s.agents[id] = a
	return a, nil
}

// Update applies field-level changes to an agent. Only non-nil pointers
// in patch take effect — the rest are left untouched. Returns the
// post-update *Agent.
type AgentPatch struct {
	Name        *string
	Description *string
	Model       *string
	Effort      *string
	Provider    *string
	Prompt      *string
}

func (s *Store) Update(id string, patch AgentPatch) (*Agent, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	cur, ok := s.agents[id]
	if !ok {
		return nil, fmt.Errorf("%w: %s", ErrNotFound, id)
	}
	cfg := *cur.Config
	cfgChanged := false
	if patch.Name != nil {
		cfg.Name = *patch.Name
		cfgChanged = true
	}
	if patch.Description != nil {
		cfg.Description = *patch.Description
		cfgChanged = true
	}
	if patch.Model != nil {
		cfg.Model = *patch.Model
		cfgChanged = true
	}
	if patch.Effort != nil {
		cfg.Effort = *patch.Effort
		cfgChanged = true
	}
	if patch.Provider != nil {
		cfg.Provider = *patch.Provider
		cfgChanged = true
	}
	if cfgChanged {
		if err := agent.SaveConfig(cur.Dir, &cfg); err != nil {
			return nil, err
		}
	}
	if patch.Prompt != nil {
		if err := os.WriteFile(filepath.Join(cur.Dir, "prompt.md"), []byte(*patch.Prompt), 0o644); err != nil {
			return nil, fmt.Errorf("write prompt.md: %w", err)
		}
	}
	a, err := loadAgent(cur.Dir)
	if err != nil {
		return nil, fmt.Errorf("reload after update: %w", err)
	}
	s.agents[id] = a
	return a, nil
}

// Delete archives an agent: moves its directory (including conversations
// and skills) to ~/.sunny/.archive/. Idempotent — missing id is not an
// error. Restoration is manual: move the timestamped folder back under
// ~/.sunny/agents/ and reload the daemon.
func (s *Store) Delete(id string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	cur, ok := s.agents[id]
	if !ok {
		return nil
	}
	archiveDir := filepath.Join(s.Root, ".archive")
	if err := os.MkdirAll(archiveDir, 0o755); err != nil {
		return err
	}
	stamp := time.Now().UTC().Format("20060102T150405Z")
	target := filepath.Join(archiveDir, fmt.Sprintf("agent__%s__%s", id, stamp))
	if err := os.Rename(cur.Dir, target); err != nil {
		return fmt.Errorf("move to archive: %w", err)
	}
	delete(s.agents, id)
	return nil
}

func Load(root string) (*Store, error) {
	agentsRoot := filepath.Join(root, "agents")
	info, err := os.Stat(agentsRoot)
	if err != nil {
		return nil, fmt.Errorf("agents dir at %s: %w", agentsRoot, err)
	}
	if !info.IsDir() {
		return nil, fmt.Errorf("%s is not a directory", agentsRoot)
	}
	entries, err := os.ReadDir(agentsRoot)
	if err != nil {
		return nil, err
	}
	s := &Store{Root: root, agents: map[string]*Agent{}}
	for _, e := range entries {
		if !e.IsDir() || strings.HasPrefix(e.Name(), ".") {
			continue
		}
		a, err := loadAgent(filepath.Join(agentsRoot, e.Name()))
		if err != nil {
			return nil, fmt.Errorf("agent %s: %w", e.Name(), err)
		}
		if _, dupe := s.agents[a.ID]; dupe {
			return nil, fmt.Errorf("agent %s: duplicate id %q (rename one of the directories)", e.Name(), a.ID)
		}
		s.agents[a.ID] = a
	}
	return s, nil
}

func loadAgent(dir string) (*Agent, error) {
	cfg, err := agent.LoadConfig(dir)
	if err != nil {
		return nil, err
	}
	knowledge, knowCats, err := loadKnowledge(filepath.Join(dir, "knowledge"))
	if err != nil {
		return nil, err
	}
	skills, skillCats, err := loadSkills(filepath.Join(dir, "skills"))
	if err != nil {
		return nil, err
	}
	prompt, err := loadPrompt(dir)
	if err != nil {
		return nil, err
	}
	return &Agent{
		ID:                  cfg.ID,
		Dir:                 dir,
		Config:              cfg,
		Knowledge:           knowledge,
		KnowledgeCategories: knowCats,
		Skills:              skills,
		SkillCategories:     skillCats,
		Prompt:              prompt,
		HasAvatar:           avatar.Path(dir) != "",
	}, nil
}

// SetHasAvatar updates the in-memory flag for id. Used by the
// avatar HTTP handlers so the next /agents response reflects the
// new state without a full reload. No-op if id isn't loaded.
func (s *Store) SetHasAvatar(id string, has bool) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if a, ok := s.agents[id]; ok {
		a.HasAvatar = has
	}
}

// Reload re-reads the agent's dir from disk and replaces the cached
// *Agent. Called at turn boundaries so any skill or knowledge file
// the agent itself wrote during a previous turn (via its provider's
// write/edit tools) shows up in the next system prompt without a
// full daemon restart. ErrNotFound when the id isn't tracked.
func (s *Store) Reload(id string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	cur, ok := s.agents[id]
	if !ok {
		return fmt.Errorf("%w: %s", ErrNotFound, id)
	}
	a, err := loadAgent(cur.Dir)
	if err != nil {
		return err
	}
	s.agents[id] = a
	return nil
}

// loadPrompt reads prompt.md from the agent dir. Returns "" (not error)
// when the file is missing — agents without a persona still load.
func loadPrompt(dir string) (string, error) {
	data, err := os.ReadFile(filepath.Join(dir, "prompt.md"))
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	return string(data), nil
}

// loadKnowledge walks dir/<category>/**/*.md and returns the flat
// file list plus the list of categories. Each top-level subdir of
// dir is a category; its description (if any) comes from INDEX.md
// inside it. INDEX.md files themselves are excluded from the file
// list — they carry category metadata, not knowledge.
func loadKnowledge(dir string) ([]KnowledgeFile, []Category, error) {
	if _, err := os.Stat(dir); os.IsNotExist(err) {
		return nil, nil, nil
	} else if err != nil {
		return nil, nil, err
	}
	catEntries, err := os.ReadDir(dir)
	if err != nil {
		return nil, nil, err
	}
	var (
		files []KnowledgeFile
		cats  []Category
	)
	for _, ce := range catEntries {
		if !ce.IsDir() || strings.HasPrefix(ce.Name(), ".") {
			continue
		}
		catDir := filepath.Join(dir, ce.Name())
		cats = append(cats, Category{
			Name:        ce.Name(),
			Description: readIndexDescription(catDir),
		})
		walkErr := filepath.WalkDir(catDir, func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() || strings.HasPrefix(d.Name(), ".") {
				return nil
			}
			if d.Name() == "INDEX.md" {
				return nil
			}
			rel, _ := filepath.Rel(dir, path)
			files = append(files, KnowledgeFile{
				Name:     filepath.ToSlash(rel),
				Category: ce.Name(),
				Path:     path,
			})
			return nil
		})
		if walkErr != nil {
			return nil, nil, walkErr
		}
	}
	sort.Slice(cats, func(i, j int) bool { return cats[i].Name < cats[j].Name })
	sort.Slice(files, func(i, j int) bool { return files[i].Name < files[j].Name })
	return files, cats, nil
}

// loadSkills walks dir/<category>/<name>/SKILL.md and returns the
// flat skill list plus the list of categories. A skill is any
// subdirectory of a category dir that contains SKILL.md.
func loadSkills(dir string) ([]*skill.Skill, []Category, error) {
	if _, err := os.Stat(dir); os.IsNotExist(err) {
		return nil, nil, nil
	} else if err != nil {
		return nil, nil, err
	}
	catEntries, err := os.ReadDir(dir)
	if err != nil {
		return nil, nil, err
	}
	var (
		skills []*skill.Skill
		cats   []Category
	)
	for _, ce := range catEntries {
		if !ce.IsDir() || strings.HasPrefix(ce.Name(), ".") {
			continue
		}
		catDir := filepath.Join(dir, ce.Name())
		cats = append(cats, Category{
			Name:        ce.Name(),
			Description: readIndexDescription(catDir),
		})
		skillEntries, err := os.ReadDir(catDir)
		if err != nil {
			return nil, nil, err
		}
		for _, se := range skillEntries {
			if !se.IsDir() || strings.HasPrefix(se.Name(), ".") {
				continue
			}
			sk, err := skill.Load(filepath.Join(catDir, se.Name()))
			if err != nil {
				return nil, nil, err
			}
			sk.Category = ce.Name()
			skills = append(skills, sk)
		}
	}
	sort.Slice(cats, func(i, j int) bool { return cats[i].Name < cats[j].Name })
	sort.Slice(skills, func(i, j int) bool {
		if skills[i].Category != skills[j].Category {
			return skills[i].Category < skills[j].Category
		}
		return skills[i].Front.Name < skills[j].Front.Name
	})
	return skills, cats, nil
}

// readIndexDescription returns the first non-empty, non-heading line
// of INDEX.md in dir, or "" if INDEX.md is missing or has no body.
// Used as the one-liner shown to agents so they can pick the right
// category when creating new skills/knowledge.
func readIndexDescription(dir string) string {
	data, err := os.ReadFile(filepath.Join(dir, "INDEX.md"))
	if err != nil {
		return ""
	}
	for _, raw := range strings.Split(string(data), "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		return line
	}
	return ""
}
