package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"strings"
	"sync/atomic"
	"syscall"
	"time"

	charmlog "charm.land/log/v2"

	"github.com/noesrafa/sunny/internal/auth"
	"github.com/noesrafa/sunny/internal/bootstrap"
	"github.com/noesrafa/sunny/internal/conversation"
	"github.com/noesrafa/sunny/internal/engine"
	"github.com/noesrafa/sunny/internal/lifecycle"
	"github.com/noesrafa/sunny/internal/logger"
	"github.com/noesrafa/sunny/internal/provider"
	"github.com/noesrafa/sunny/internal/provider/anthropic"
	"github.com/noesrafa/sunny/internal/provider/claudecode"
	"github.com/noesrafa/sunny/internal/provider/ollama"
	"github.com/noesrafa/sunny/internal/secrets"
	"github.com/noesrafa/sunny/internal/server"
	"github.com/noesrafa/sunny/internal/session"
	uistate "github.com/noesrafa/sunny/internal/state"
	"github.com/noesrafa/sunny/internal/store"
	"github.com/noesrafa/sunny/internal/tui"
)

// version is set by the linker at release time via -ldflags. For local
// `go build` it stays as "dev".
var version = "dev"

func main() {
	if len(os.Args) < 2 {
		// `sunny` with no arguments opens the TUI against the default daemon.
		if err := openTUI(nil); err != nil {
			fmt.Fprintln(os.Stderr, "error:", err)
			os.Exit(1)
		}
		return
	}
	cmd := os.Args[1]
	args := os.Args[2:]
	var err error
	switch cmd {
	case "tui":
		err = openTUI(args)
	case "start":
		err = start(args)
	case "stop":
		err = stop(args)
	case "status":
		err = status(args)
	case "serve":
		err = serve(args)
	case "token":
		err = token(args)
	case "secrets":
		err = secretsCmd(args)
	case "version", "-v", "--version":
		fmt.Println("sunny", version)
	case "help", "-h", "--help":
		usage()
	default:
		fmt.Fprintln(os.Stderr, "unknown command:", cmd)
		usage()
		os.Exit(2)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}

func usage() {
	fmt.Fprintln(os.Stderr, `usage: sunny [command] [args]

commands:
  (none)    Open the TUI (alias for 'tui').
  tui       Open the TUI client. --addr selects which daemon to connect to.
  start     Run the daemon detached. Logs to <root>/run/sunny.log.
  stop      Stop the running daemon.
  status    Show whether the daemon is running, plus pid, addr, uptime.
  serve     Run the daemon in the foreground (advanced; prefer 'start').
  token     Print the daemon's bearer token. 'sunny token rotate' regenerates it.
  secrets   Manage provider keys. 'sunny secrets' lists, 'sunny secrets <p> set <field>' reads from stdin.
  version   Print version.

common flags:
  --addr   HTTP listen address (default 127.0.0.1:7777)
  --root   sunny runtime directory (default ~/.sunny)`)
}

func openTUI(args []string) error {
	fs := flag.NewFlagSet("tui", flag.ExitOnError)
	addr := fs.String("addr", "127.0.0.1:7777", "daemon address to connect to")
	root := fs.String("root", defaultRoot(), "sunny runtime directory")
	noAutoStart := fs.Bool("no-auto-start", false, "skip auto-starting the daemon if it isn't running")
	if err := fs.Parse(args); err != nil {
		return err
	}

	// Auto-start the daemon when it isn't already running. The TUI is
	// useless without a daemon; making the user remember `sunny start`
	// before `sunny` is the wrong default. --no-auto-start opts out for
	// users who want the legacy behavior or who manage the daemon
	// out-of-band (systemd, launchd, etc.).
	if !*noAutoStart {
		paths := lifecycle.PathsFor(*root)
		alive := false
		if s, err := paths.LoadState(); err == nil && lifecycle.IsAlive(s.PID) {
			alive = true
			*addr = s.Addr // honor whatever addr the running daemon is on
		}
		if !alive {
			fmt.Fprintf(os.Stderr, "sunny: daemon not running — starting it on %s…\n", *addr)
			s, err := startDaemon(*addr, *root, true)
			if err != nil {
				return fmt.Errorf("auto-start: %w", err)
			}
			*addr = s.Addr
		}
	}

	// Token is generated by the daemon on its first boot. By the time
	// we get here the daemon is alive (either pre-existing or just
	// auto-started) so the file must exist.
	tok, err := auth.LoadToken(*root)
	if err != nil {
		return fmt.Errorf("load token: %w (daemon may not have written it yet)", err)
	}

	cwd, _ := os.Getwd()

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	lg, closer := logger.Setup("sunny")
	defer closer.Close()
	lg.Info("tui starting", "cwd", cwd, "log", logger.LogPath())

	mgr := session.NewManager()
	saved, themeID, activeIdx := loadSavedState(lg)
	if len(saved) > 0 {
		for _, ss := range saved {
			restored, err := restoreSession(ctx, lg, ss)
			if err != nil {
				lg.Warn("restore session failed; skipping", "title", ss.Title, "err", err)
				continue
			}
			mgr.Add(restored)
		}
	}
	if mgr.Len() == 0 {
		// First launch (or all restores failed) — bootstrap one fresh
		// session bound to the default agent.
		first, err := session.New(ctx, cwd, session.Options{
			Logger:    lg,
			Title:     "sunny",
			AgentSlug: "sunny",
		})
		if err != nil {
			return fmt.Errorf("create session: %w", err)
		}
		mgr.Add(first)
	} else if activeIdx >= 0 && activeIdx < mgr.Len() {
		mgr.Active = activeIdx
	}

	first := mgr.Sessions[0]
	model := tui.NewModel(ctx, mgr, cwd, tui.Options{
		Logger:                   lg,
		DefaultModel:             first.Model,
		DefaultEffort:            first.Effort,
		DangerousSkipPermissions: true,
		DaemonAddr:               *addr,
		DaemonToken:              tok,
		DefaultAgent:             "sunny",
		InitialTheme:             themeID,
	})
	return model.Run(ctx)
}

// loadSavedState reads ~/.sunny/state.json and returns the sessions to
// restore plus the theme id. Failures fall back to a fresh launch with
// no sessions; the caller will bootstrap one.
func loadSavedState(lg *charmlog.Logger) ([]uistate.SavedSession, string, int) {
	st, err := uistate.Load()
	if err != nil {
		lg.Warn("load state failed; starting fresh", "err", err)
		return nil, "", 0
	}
	return st.Sessions, st.Theme, st.ActiveIdx
}

// restoreSession rebuilds a Session from its saved form. The transcript
// is decoded from the cached Items blob; ConvID and AgentSlug are
// preserved so the next send hits the same server-side conversation.
// AgentSlug falls back to "sunny" for legacy state files without it.
func restoreSession(ctx context.Context, lg *charmlog.Logger, ss uistate.SavedSession) (*session.Session, error) {
	items, err := session.UnmarshalItems(ss.Items)
	if err != nil {
		return nil, fmt.Errorf("decode items: %w", err)
	}
	slug := ss.AgentSlug
	if slug == "" {
		slug = "sunny"
	}
	return session.New(ctx, ss.Cwd, session.Options{
		Logger:    lg,
		Title:     ss.Title,
		Model:     ss.Model,
		Effort:    ss.Effort,
		Draft:     ss.Draft,
		AgentSlug: slug,
		ConvID:    ss.ConvID,
		Items:     items,
		TotalCost: ss.TotalCost,
		Turns:     ss.Turns,
	})
}

func defaultRoot() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ".sunny"
	}
	return filepath.Join(home, ".sunny")
}

// buildEngine attempts to instantiate every supported provider and
// returns an Engine indexing all the ones that succeeded. The default
// provider is the first one to come up (in declaration order below),
// or whatever SUNNY_PROVIDER pins.
//
// Order matters: claude-code wins by default because it inherits the
// user's claude.ai login (no separate API key) AND brings claude
// code's full toolset. Anthropic API + Ollama Cloud both depend on
// `secrets.yaml` (or env-var equivalents) being populated.
//
// Returning a zero-engine (no providers) is OK — chat endpoints will
// return 503 until at least one driver is configured.
func buildEngine(log *slog.Logger, s *secrets.Store) *engine.Engine {
	choice := strings.ToLower(strings.TrimSpace(os.Getenv("SUNNY_PROVIDER")))
	if choice == "off" {
		log.Info("engine disabled", "reason", "SUNNY_PROVIDER=off")
		return engine.New(nil, "")
	}

	registry := map[string]provider.Provider{}
	var defaultName string

	tryAdd := func(name string, drv provider.Provider, err error) {
		if err != nil {
			log.Debug("provider skipped", "name", name, "reason", err.Error())
			return
		}
		registry[name] = drv
		log.Info("provider ready", "name", name)
	}

	cc, ccErr := claudecode.New()
	tryAdd("claude-code", cc, ccErr)
	an, anErr := anthropic.New(s)
	tryAdd("anthropic", an, anErr)
	ol, olErr := ollama.New(s)
	tryAdd("ollama", ol, olErr)

	// Pick default. Explicit SUNNY_PROVIDER wins; otherwise first
	// registered in declaration order (claude-code → anthropic → ollama).
	switch choice {
	case "claude-code", "claude_code", "claudecode":
		if _, ok := registry["claude-code"]; ok {
			defaultName = "claude-code"
		} else {
			log.Warn("SUNNY_PROVIDER=claude-code but claude CLI not available")
		}
	case "anthropic":
		if _, ok := registry["anthropic"]; ok {
			defaultName = "anthropic"
		} else {
			log.Warn("SUNNY_PROVIDER=anthropic but api_key not configured")
		}
	case "ollama":
		if _, ok := registry["ollama"]; ok {
			defaultName = "ollama"
		} else {
			log.Warn("SUNNY_PROVIDER=ollama but api_key not configured")
		}
	}
	if defaultName == "" {
		for _, n := range []string{"claude-code", "anthropic", "ollama"} {
			if _, ok := registry[n]; ok {
				defaultName = n
				break
			}
		}
	}
	if defaultName == "" {
		log.Warn("no providers available — configure one via `sunny secrets <provider> set api_key` or install claude code")
	}
	return engine.New(registry, defaultName)
}

// quiet compile-time check that drivers satisfy provider.Provider.
var (
	_ provider.Provider = (*anthropic.Driver)(nil)
	_ provider.Provider = (*claudecode.Driver)(nil)
	_ provider.Provider = (*ollama.Driver)(nil)
)

// serve runs the daemon in the foreground. Used by `start` (re-exec'd as a
// detached child) and directly when debugging.
func serve(args []string) error {
	fs := flag.NewFlagSet("serve", flag.ExitOnError)
	addr := fs.String("addr", "127.0.0.1:7777", "HTTP listen address")
	root := fs.String("root", defaultRoot(), "sunny runtime directory")
	if err := fs.Parse(args); err != nil {
		return err
	}

	log := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelInfo}))

	seeded, err := bootstrap.EnsureRuntime(*root)
	if err != nil {
		return fmt.Errorf("bootstrap: %w", err)
	}
	if seeded {
		log.Info("seeded runtime from defaults", "root", *root)
	} else {
		log.Info("using existing runtime", "root", *root)
	}

	st, err := store.Load(*root)
	if err != nil {
		return fmt.Errorf("load store: %w", err)
	}
	log.Info("store loaded", "agents", len(st.Agents()))

	tok, err := auth.EnsureToken(*root)
	if err != nil {
		return fmt.Errorf("ensure token: %w", err)
	}
	log.Info("auth ready", "token_path", auth.Path(*root))

	secretsStore, err := secrets.New(*root)
	if err != nil {
		return fmt.Errorf("load secrets: %w", err)
	}
	log.Info("secrets ready", "path", secrets.Path(*root))

	// Engine is held in an atomic.Pointer so PUT /secrets can swap it
	// in place — provider drivers re-read on each Stream(), but the
	// auto-detect chain runs at construction so newly-configured
	// providers need a rebuild to enter the registry.
	var enginePtr atomic.Pointer[engine.Engine]
	enginePtr.Store(buildEngine(log, secretsStore))
	convs := conversation.NewStore(*root)

	rebuild := func() {
		log.Info("rebuilding engine after secrets change")
		enginePtr.Store(buildEngine(log, secretsStore))
	}

	srv := &http.Server{
		Addr: *addr,
		Handler: server.New(server.Options{
			Store:         st,
			Conversations: convs,
			Secrets:       secretsStore,
			Engine:        &enginePtr,
			Log:           log,
			Token:         tok,
			RebuildEngine: rebuild,
		}),
		ReadHeaderTimeout: 5 * time.Second,
	}

	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer cancel()

	errCh := make(chan error, 1)
	go func() {
		log.Info("listening", "addr", *addr)
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			errCh <- err
		}
	}()

	select {
	case err := <-errCh:
		return err
	case <-ctx.Done():
		log.Info("shutting down")
		shutdownCtx, c := context.WithTimeout(context.Background(), 5*time.Second)
		defer c()
		return srv.Shutdown(shutdownCtx)
	}
}

func start(args []string) error {
	fs := flag.NewFlagSet("start", flag.ExitOnError)
	addr := fs.String("addr", "127.0.0.1:7777", "HTTP listen address")
	root := fs.String("root", defaultRoot(), "sunny runtime directory")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if _, err := startDaemon(*addr, *root, false); err != nil {
		return err
	}
	return nil
}

// startDaemon spawns the daemon detached and waits for healthz. When
// ifNotRunning is true and the daemon is already alive at the recorded
// addr, it returns the existing state without spawning. Used by `sunny
// start` (ifNotRunning=false → errors on duplicate) and the no-arg
// auto-start flow (ifNotRunning=true → silently reuses).
func startDaemon(addr, root string, ifNotRunning bool) (*lifecycle.State, error) {
	paths := lifecycle.PathsFor(root)

	if s, err := paths.LoadState(); err == nil {
		if lifecycle.IsAlive(s.PID) {
			if ifNotRunning {
				return s, nil
			}
			return nil, fmt.Errorf("already running (pid=%d, addr=%s) — `sunny stop` first", s.PID, s.Addr)
		}
		_ = paths.ClearState()
	}

	if err := os.MkdirAll(paths.Run, 0o755); err != nil {
		return nil, fmt.Errorf("create run dir: %w", err)
	}

	logFile, err := os.OpenFile(paths.Log, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		return nil, fmt.Errorf("open log: %w", err)
	}
	defer logFile.Close()

	binary, err := os.Executable()
	if err != nil {
		return nil, fmt.Errorf("resolve self: %w", err)
	}

	cmd := exec.Command(binary, "serve", "--addr", addr, "--root", root)
	cmd.Stdout = logFile
	cmd.Stderr = logFile
	cmd.SysProcAttr = &syscall.SysProcAttr{Setsid: true}
	if err := cmd.Start(); err != nil {
		return nil, fmt.Errorf("spawn: %w", err)
	}

	state := &lifecycle.State{
		PID:       cmd.Process.Pid,
		Addr:      addr,
		StartedAt: time.Now(),
		Binary:    binary,
	}
	if err := paths.SaveState(state); err != nil {
		_ = cmd.Process.Kill()
		return nil, fmt.Errorf("save state: %w", err)
	}

	if err := waitHealthy(addr, cmd.Process.Pid, 3*time.Second); err != nil {
		// Daemon failed to come up. Reap and clean state so the next
		// invocation gets a fresh attempt instead of inheriting stale
		// state.json. Surface the tail of the log so the caller can
		// diagnose without grepping by hand.
		if lifecycle.IsAlive(cmd.Process.Pid) {
			_ = cmd.Process.Kill()
		}
		_ = paths.ClearState()
		if tail := tailLog(paths.Log, 20); tail != "" {
			return nil, fmt.Errorf("%w\n--- last lines of %s ---\n%s", err, paths.Log, tail)
		}
		return nil, fmt.Errorf("%w (see %s)", err, paths.Log)
	}

	fmt.Printf("started  pid=%d  addr=%s  log=%s\n", state.PID, addr, paths.Log)
	return state, nil
}

func stop(args []string) error {
	fs := flag.NewFlagSet("stop", flag.ExitOnError)
	root := fs.String("root", defaultRoot(), "sunny runtime directory")
	timeout := fs.Duration("timeout", 5*time.Second, "graceful shutdown wait before SIGKILL")
	if err := fs.Parse(args); err != nil {
		return err
	}

	paths := lifecycle.PathsFor(*root)
	state, err := paths.LoadState()
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			fmt.Println("not running")
			return nil
		}
		return err
	}

	if !lifecycle.IsAlive(state.PID) {
		_ = paths.ClearState()
		fmt.Printf("stale state cleaned up (pid=%d was not alive)\n", state.PID)
		return nil
	}

	proc, err := os.FindProcess(state.PID)
	if err != nil {
		return err
	}
	if err := proc.Signal(syscall.SIGTERM); err != nil {
		return fmt.Errorf("signal: %w", err)
	}

	deadline := time.Now().Add(*timeout)
	for time.Now().Before(deadline) {
		if !lifecycle.IsAlive(state.PID) {
			_ = paths.ClearState()
			fmt.Printf("stopped  pid=%d\n", state.PID)
			return nil
		}
		time.Sleep(100 * time.Millisecond)
	}

	_ = proc.Signal(syscall.SIGKILL)
	_ = paths.ClearState()
	fmt.Printf("stopped  pid=%d  (SIGKILL after %s)\n", state.PID, *timeout)
	return nil
}

func status(args []string) error {
	fs := flag.NewFlagSet("status", flag.ExitOnError)
	root := fs.String("root", defaultRoot(), "sunny runtime directory")
	if err := fs.Parse(args); err != nil {
		return err
	}

	paths := lifecycle.PathsFor(*root)
	state, err := paths.LoadState()
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			fmt.Println("not running")
			return nil
		}
		return err
	}

	if !lifecycle.IsAlive(state.PID) {
		fmt.Printf("stale     pid=%d not alive — run `sunny stop` to clean up\n", state.PID)
		return nil
	}

	uptime := time.Since(state.StartedAt).Round(time.Second)
	fmt.Printf("status:   running\n")
	fmt.Printf("pid:      %d\n", state.PID)
	fmt.Printf("addr:     %s\n", state.Addr)
	fmt.Printf("uptime:   %s\n", uptime)
	fmt.Printf("root:     %s\n", paths.Root)
	fmt.Printf("log:      %s\n", paths.Log)

	if err := pingHealth(state.Addr, 1*time.Second); err == nil {
		fmt.Printf("healthz:  ok\n")
	} else {
		fmt.Printf("healthz:  %v\n", err)
	}
	return nil
}

// secretsCmd is the CLI surface for ~/.sunny/secrets.yaml. Subcommands:
//
//	sunny secrets                       → list configured providers + fields
//	sunny secrets <provider>            → show fields for that provider
//	sunny secrets <provider> set <fld>  → read value from stdin, save
//	sunny secrets <provider> delete     → remove provider section
//
// `set` reads from stdin so the value never lands in shell history /
// `ps`. Pipe it: `pbpaste | sunny secrets anthropic set api_key`,
// or run without stdin and the prompt asks interactively.
//
// Writes go straight to ~/.sunny/secrets.yaml. The running daemon
// re-reads the file on next access (provider drivers consult the
// store fresh every Stream call), so no restart is required for the
// new value to take effect — but the daemon's *registry* (which
// providers exist) only updates on next boot or after a
// PUT /secrets via HTTP.
func secretsCmd(args []string) error {
	fs := flag.NewFlagSet("secrets", flag.ExitOnError)
	root := fs.String("root", defaultRoot(), "sunny runtime directory")
	if err := fs.Parse(args); err != nil {
		return err
	}
	rest := fs.Args()
	store, err := secrets.New(*root)
	if err != nil {
		return err
	}

	switch len(rest) {
	case 0:
		return secretsList(store)
	case 1:
		return secretsShow(store, rest[0])
	}
	provider := rest[0]
	switch rest[1] {
	case "set":
		if len(rest) != 3 {
			return fmt.Errorf("usage: sunny secrets %s set <field>", provider)
		}
		return secretsSet(store, provider, rest[2])
	case "delete", "remove", "rm":
		if err := store.Delete(provider); err != nil {
			return err
		}
		fmt.Printf("removed %s\n", provider)
		return nil
	}
	return fmt.Errorf("unknown subcommand: %s", strings.Join(rest[1:], " "))
}

func secretsList(s *secrets.Store) error {
	infos := s.List()
	if len(infos) == 0 {
		fmt.Println("(no secrets configured)")
		fmt.Println("try: sunny secrets anthropic set api_key")
		return nil
	}
	for _, i := range infos {
		fmt.Printf("%-12s %s\n", i.Provider, strings.Join(i.Fields, ", "))
	}
	return nil
}

func secretsShow(s *secrets.Store, provider string) error {
	for _, i := range s.List() {
		if i.Provider == provider {
			if len(i.Fields) == 0 {
				fmt.Println("(no fields)")
				return nil
			}
			for _, f := range i.Fields {
				fmt.Printf("%s ✓\n", f)
			}
			return nil
		}
	}
	fmt.Printf("%s: not configured\n", provider)
	return nil
}

func secretsSet(s *secrets.Store, provider, field string) error {
	stat, _ := os.Stdin.Stat()
	piped := (stat.Mode() & os.ModeCharDevice) == 0
	var value string
	if piped {
		raw, err := os.ReadFile("/dev/stdin")
		if err != nil {
			return fmt.Errorf("read stdin: %w", err)
		}
		value = strings.TrimSpace(string(raw))
	} else {
		fmt.Fprintf(os.Stderr, "value for %s.%s (will not echo): ", provider, field)
		// Best-effort: read a line. We don't disable echo (no x/term
		// dep) — recommend piping for sensitive values. Print a
		// reminder to stderr.
		var line string
		if _, err := fmt.Fscanln(os.Stdin, &line); err != nil {
			return fmt.Errorf("read input: %w", err)
		}
		value = strings.TrimSpace(line)
	}
	if value == "" {
		return fmt.Errorf("empty value — refusing to save")
	}
	if err := s.SetField(provider, field, value); err != nil {
		return err
	}
	fmt.Printf("saved %s.%s\n", provider, field)
	fmt.Fprintln(os.Stderr, "(running daemon picks up the new value on next request; no restart needed)")
	return nil
}

// waitHealthy polls /healthz until it returns OK or until the spawned
// daemon process exits. The PID check shortcuts the timeout when the
// daemon crashes during boot — without it, callers waste 3s waiting on a
// corpse.
// token prints the current bearer token, or rotates it. Usage:
//
//	sunny token         → print the current token
//	sunny token rotate  → generate a new one, print it, invalidate the old
func token(args []string) error {
	fs := flag.NewFlagSet("token", flag.ExitOnError)
	root := fs.String("root", defaultRoot(), "sunny runtime directory")
	if err := fs.Parse(args); err != nil {
		return err
	}
	rest := fs.Args()
	switch {
	case len(rest) == 0:
		tok, err := auth.LoadToken(*root)
		if err != nil {
			if errors.Is(err, os.ErrNotExist) {
				return fmt.Errorf("no token at %s — start the daemon at least once first", auth.Path(*root))
			}
			return err
		}
		fmt.Println(tok)
		return nil
	case len(rest) == 1 && rest[0] == "rotate":
		tok, err := auth.Rotate(*root)
		if err != nil {
			return err
		}
		fmt.Println(tok)
		fmt.Fprintln(os.Stderr, "rotated — restart the daemon (`sunny stop && sunny start`) and any open TUI sessions for it to take effect")
		return nil
	default:
		return fmt.Errorf("unknown token subcommand: %s", strings.Join(rest, " "))
	}
}

func waitHealthy(addr string, pid int, timeout time.Duration) error {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		if err := pingHealth(addr, 200*time.Millisecond); err == nil {
			return nil
		}
		if !lifecycle.IsAlive(pid) {
			return fmt.Errorf("daemon process exited before becoming healthy")
		}
		time.Sleep(50 * time.Millisecond)
	}
	return fmt.Errorf("not healthy after %s", timeout)
}

// tailLog returns the last n lines of the file at path, or "" if the
// file can't be read. Best-effort — bounded by reading the whole file
// since sunny.log stays small in practice.
func tailLog(path string, n int) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	lines := strings.Split(strings.TrimRight(string(data), "\n"), "\n")
	if len(lines) > n {
		lines = lines[len(lines)-n:]
	}
	return strings.Join(lines, "\n")
}

func pingHealth(addr string, timeout time.Duration) error {
	client := &http.Client{Timeout: timeout}
	resp, err := client.Get("http://" + addr + "/healthz")
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("status %d", resp.StatusCode)
	}
	return nil
}
